import type { PricingPlan, Testimonial, FAQItem, BlogPost, DashboardStat, Alert, CameraFeed } from '@/types';

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: { monthly: 149, annual: 119 },
    description: 'Perfect for small teams and proof-of-concept deployments.',
    features: [
      'Up to 5 camera streams',
      'Object detection & classification',
      'Basic OCR processing',
      'Email alerts',
      '10,000 API calls/month',
      '30-day data retention',
      'Community support',
    ],
    highlighted: false,
    cta: 'Start Free Trial',
  },
  {
    id: 'professional',
    name: 'Professional',
    price: { monthly: 499, annual: 399 },
    description: 'Ideal for growing enterprises with advanced vision needs.',
    features: [
      'Up to 50 camera streams',
      'All AI detection modules',
      'Facial recognition',
      'Custom model training',
      'Real-time video analytics',
      '500,000 API calls/month',
      '90-day data retention',
      'Priority support',
      'REST API & webhooks',
      'SSO integration',
    ],
    highlighted: true,
    cta: 'Start Free Trial',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: { monthly: 0, annual: 0 },
    description: 'Unlimited scale with enterprise-grade security and compliance.',
    features: [
      'Unlimited camera streams',
      'All Professional features',
      'Edge AI deployment',
      'Custom model fine-tuning',
      'Unlimited API calls',
      'Unlimited data retention',
      'Dedicated support team',
      'On-premise deployment',
      'Custom integrations',
      'SLA guarantee',
      'Compliance controls',
    ],
    highlighted: false,
    cta: 'Contact Sales',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    role: 'VP of Operations',
    company: 'NexaManufacturing',
    content: 'VisionEx transformed our quality control. Defect detection rates improved by 94% and we reduced manual inspection costs by $2.3M annually. The real-time alerts are game-changing.',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: '2',
    name: 'Marcus Rodriguez',
    role: 'Chief Security Officer',
    company: 'Meridian Finance',
    content: 'The facial recognition and intrusion detection are incredibly accurate. We\'ve reduced security incidents by 78% since deploying VisionEx across our 12 office locations.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: '3',
    name: 'Dr. Priya Sharma',
    role: 'AI Research Lead',
    company: 'TechVision Labs',
    content: 'The custom model training platform is exceptional. We built and deployed specialized detection models in days, not months. The transfer learning capabilities are world-class.',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: '4',
    name: 'James Park',
    role: 'Director of Smart Cities',
    company: 'Urban Intelligence Corp',
    content: 'Deployed VisionEx for traffic monitoring across 200+ intersections. The vehicle recognition and crowd analytics have significantly improved our city\'s traffic management.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: '5',
    name: 'Emily Walsh',
    role: 'Head of Retail Technology',
    company: 'RetailChain Global',
    content: 'Shelf analytics and customer behavior insights from VisionEx helped us optimize store layouts, resulting in a 23% increase in conversion rates across 300 stores.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: '6',
    name: 'Ahmed Hassan',
    role: 'CTO',
    company: 'SafeGuard Security',
    content: 'The edge AI capabilities are remarkable. We process video on-device for maximum privacy, and the accuracy is on par with cloud solutions. Integration took less than a week.',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: '1',
    question: 'What types of cameras and video sources does VisionEx support?',
    answer: 'VisionEx supports IP cameras (RTSP/RTMP), USB cameras, CCTV systems, cloud storage (AWS S3, Google Cloud), direct file uploads (MP4, AVI, MOV, images), and IoT sensor integrations. We support H.264, H.265, MJPEG and most standard video codecs.',
    category: 'Technical',
  },
  {
    id: '2',
    question: 'How accurate is the AI detection and can I improve it?',
    answer: 'Our pre-trained models achieve 95-98% accuracy on standard detection tasks. Accuracy depends on lighting, camera quality, and use case. You can improve accuracy by training custom models with your own labeled data using our AI Training module, which uses transfer learning to adapt models to your specific environment.',
    category: 'AI',
  },
  {
    id: '3',
    question: 'Does VisionEx support on-premise and edge deployment?',
    answer: 'Yes. Enterprise plans include full on-premise deployment options and edge AI capabilities. Our edge deployment supports NVIDIA Jetson, AWS Greengrass, and custom ARM/x86 hardware, enabling offline processing without sending video to the cloud.',
    category: 'Deployment',
  },
  {
    id: '4',
    question: 'How is video data stored and kept secure?',
    answer: 'All video data is encrypted at rest (AES-256) and in transit (TLS 1.3). We are SOC 2 Type II certified and GDPR compliant. Video processing happens in isolated environments, and you control data retention policies. Enterprise plans support private cloud and on-premise deployments for maximum data sovereignty.',
    category: 'Security',
  },
  {
    id: '5',
    question: 'What integrations does VisionEx support?',
    answer: 'VisionEx offers REST APIs, webhooks, and SDKs for Python, Node.js, Java, and Go. Pre-built integrations include Slack, PagerDuty, Microsoft Teams, Salesforce, ServiceNow, SAP, and major ERP systems. Custom integrations are available for Enterprise plans.',
    category: 'Integration',
  },
  {
    id: '6',
    question: 'Can I train custom AI models for my specific use case?',
    answer: 'Absolutely. Our AI Training module lets you upload and annotate datasets, fine-tune pre-trained models using transfer learning, evaluate model performance with detailed metrics, and deploy models to production with one click. No deep ML expertise is required.',
    category: 'AI',
  },
  {
    id: '7',
    question: 'What is the pricing model and are there hidden fees?',
    answer: 'VisionEx pricing is transparent with no hidden fees. Plans are based on number of camera streams and API calls. Additional usage beyond plan limits is charged at published overage rates. Annual plans save up to 20%. Enterprise plans include custom pricing with volume discounts.',
    category: 'Pricing',
  },
  {
    id: '8',
    question: 'How long does it take to get started?',
    answer: 'Most teams are up and running within hours. Connect your first camera, choose your detection models, and configure alerts in under 30 minutes. Our onboarding team provides guided setup for enterprise deployments, and detailed documentation is available for self-service setup.',
    category: 'Getting Started',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'How AI Computer Vision is Transforming Manufacturing Quality Control',
    excerpt: 'Discover how leading manufacturers are using VisionEx to achieve 99% defect detection rates and reduce inspection costs by over 60%.',
    category: 'Manufacturing',
    author: 'Dr. James Liu',
    date: 'Jan 15, 2025',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop',
    slug: 'ai-manufacturing-quality-control',
  },
  {
    id: '2',
    title: 'Real-Time Facial Recognition in Access Control: A Complete Guide',
    excerpt: 'A deep dive into implementing enterprise-grade facial recognition for building access control, visitor management, and attendance tracking.',
    category: 'Security',
    author: 'Sarah Mitchell',
    date: 'Jan 22, 2025',
    readTime: '12 min read',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop',
    slug: 'facial-recognition-access-control',
  },
  {
    id: '3',
    title: 'Edge AI vs Cloud AI for Video Analytics: Choosing the Right Architecture',
    excerpt: 'Compare edge and cloud deployment models for video analytics workloads, including latency, cost, privacy, and scalability considerations.',
    category: 'Technology',
    author: 'Raj Patel',
    date: 'Feb 3, 2025',
    readTime: '10 min read',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop',
    slug: 'edge-ai-vs-cloud-ai-video-analytics',
  },
  {
    id: '4',
    title: 'Building Custom Vision Models Without Deep ML Expertise',
    excerpt: 'A step-by-step walkthrough of creating, training, and deploying custom object detection models using VisionEx\'s no-code AI training platform.',
    category: 'AI & ML',
    author: 'Emily Chen',
    date: 'Feb 14, 2025',
    readTime: '15 min read',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=400&fit=crop',
    slug: 'custom-vision-models-no-code',
  },
  {
    id: '5',
    title: 'Smart City Traffic Monitoring with AI Vision: Case Study',
    excerpt: 'How Urban Intelligence Corp used VisionEx to monitor 200+ intersections, reduce congestion by 35%, and improve emergency response times.',
    category: 'Smart Cities',
    author: 'Marcus Green',
    date: 'Feb 28, 2025',
    readTime: '9 min read',
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=600&h=400&fit=crop',
    slug: 'smart-city-traffic-monitoring',
  },
  {
    id: '6',
    title: 'GDPR Compliance in AI Video Surveillance: What You Need to Know',
    excerpt: 'A practical guide to deploying AI video analytics while maintaining full GDPR compliance, including data minimization, consent, and retention policies.',
    category: 'Compliance',
    author: 'Anna Weber',
    date: 'Mar 8, 2025',
    readTime: '11 min read',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&h=400&fit=crop',
    slug: 'gdpr-compliance-ai-video-surveillance',
  },
];

export const DASHBOARD_STATS: DashboardStat[] = [
  { label: 'Active Streams', value: '47', change: '+3', changeType: 'positive', icon: 'Video' },
  { label: 'Detections Today', value: '12,847', change: '+18.3%', changeType: 'positive', icon: 'Eye' },
  { label: 'Active Alerts', value: '8', change: '-2', changeType: 'positive', icon: 'Bell' },
  { label: 'Model Accuracy', value: '97.4%', change: '+0.2%', changeType: 'positive', icon: 'Target' },
];

export const SAMPLE_ALERTS: Alert[] = [
  { id: '1', type: 'intrusion', severity: 'high', message: 'Unauthorized access detected in restricted zone', location: 'Server Room B', timestamp: '2 min ago', status: 'new' },
  { id: '2', type: 'defect', severity: 'medium', message: 'Surface defect detected on product batch #4821', location: 'Production Line 3', timestamp: '8 min ago', status: 'new' },
  { id: '3', type: 'motion', severity: 'low', message: 'Motion detected outside business hours', location: 'Parking Lot C', timestamp: '15 min ago', status: 'acknowledged' },
  { id: '4', type: 'face', severity: 'medium', message: 'Unknown individual in secure area', location: 'R&D Lab', timestamp: '32 min ago', status: 'acknowledged' },
  { id: '5', type: 'vehicle', severity: 'low', message: 'Unregistered vehicle in reserved zone', location: 'Loading Bay 2', timestamp: '1 hr ago', status: 'resolved' },
];

export const CAMERA_FEEDS: CameraFeed[] = [
  { id: '1', name: 'Main Entrance', location: 'Building A', status: 'online', detections: 234, thumbnail: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=300&h=200&fit=crop' },
  { id: '2', name: 'Production Line 1', location: 'Factory Floor', status: 'online', detections: 1847, thumbnail: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=300&h=200&fit=crop' },
  { id: '3', name: 'Server Room', location: 'Data Center', status: 'online', detections: 56, thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=300&h=200&fit=crop' },
  { id: '4', name: 'Parking Lot A', location: 'Exterior', status: 'processing', detections: 389, thumbnail: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=300&h=200&fit=crop' },
  { id: '5', name: 'Lobby Camera', location: 'Building B', status: 'online', detections: 612, thumbnail: 'https://images.unsplash.com/photo-1497366412874-3415097a27e7?w=300&h=200&fit=crop' },
  { id: '6', name: 'Loading Dock', location: 'Warehouse', status: 'offline', detections: 0, thumbnail: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?w=300&h=200&fit=crop' },
];
