import { useScrollTop } from '@/hooks/useScrollTop';
import { Shield, Lock, Eye, Database, Cookie, Globe } from 'lucide-react';

const SECTIONS = [
  {
    id: 'collection',
    icon: Database,
    title: '1. Information We Collect',
    content: `We collect information you provide directly (account registration, forms, communications), information generated by your use of the platform (usage logs, analytics, API calls), and information from your connected data sources (camera feeds, uploaded images/videos, documents).

**Account Information:** Name, email address, company name, billing information, and authentication credentials.

**Platform Usage:** Feature interactions, API calls, detection events, model training jobs, and system performance metrics.

**Visual Data:** Images and video streams processed through our AI engine. This data is processed according to your configuration and is never used to train our base models without explicit consent.`,
  },
  {
    id: 'use',
    icon: Eye,
    title: '2. How We Use Your Information',
    content: `We use the information we collect to: provide and improve the VisionEx platform; process your AI detection jobs; send transactional communications; provide customer support; comply with legal obligations; and prevent fraud and abuse.

We do not sell your personal information or your visual data to third parties. We do not use your data to train our core AI models without explicit written agreement.`,
  },
  {
    id: 'security',
    icon: Lock,
    title: '3. Data Security',
    content: `VisionEx employs industry-leading security practices including: AES-256 encryption for data at rest; TLS 1.3 for all data in transit; SOC 2 Type II certified infrastructure; isolated customer environments; regular third-party penetration testing; and 24/7 security monitoring.

Access to customer data is strictly limited to authorized personnel and only when necessary for support or legal compliance.`,
  },
  {
    id: 'gdpr',
    icon: Globe,
    title: '4. GDPR & International Compliance',
    content: `For customers in the European Economic Area (EEA), VisionEx acts as a data processor for visual data and a data controller for account information. We maintain Standard Contractual Clauses (SCCs) for international data transfers.

Your rights include: access to your data; correction of inaccurate data; deletion of your data; data portability; and the right to restrict processing. To exercise these rights, contact privacy@visionex.ai.`,
  },
  {
    id: 'cookies',
    icon: Cookie,
    title: '5. Cookies & Tracking',
    content: `We use strictly necessary cookies for authentication and session management, functional cookies for preferences and settings, and analytics cookies (with consent) to understand platform usage patterns.

You can manage cookie preferences through your browser settings or our cookie consent interface. Disabling functional cookies may impact platform functionality.`,
  },
  {
    id: 'retention',
    icon: Shield,
    title: '6. Data Retention',
    content: `Retention periods vary by data type and plan: account data is retained for the duration of your subscription plus 90 days; detection events and analytics for 30 days (Starter), 90 days (Professional), or as configured (Enterprise); visual media according to your storage settings; audit logs for 12 months.

You may delete your data at any time through the Settings panel or by contacting support.`,
  },
];

export default function Privacy() {
  useScrollTop();

  return (
    <div className="page-transition min-h-screen bg-background">
      <section className="relative pt-28 pb-16 overflow-hidden">
        <div className="absolute inset-0 bg-grid-pattern dark:bg-grid-pattern-dark" />
        <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-indigo-500/30 bg-indigo-600/10 text-indigo-400 text-xs font-medium mb-4">
            <Shield className="w-3.5 h-3.5" /> Privacy & Data Protection
          </div>
          <h1 className="font-heading text-4xl sm:text-5xl font-bold text-foreground mb-4">
            Privacy <span className="text-gradient-indigo-cyan">Policy</span>
          </h1>
          <p className="text-muted-foreground max-w-xl mx-auto mb-4">
            We are committed to protecting your data and being transparent about how we use it.
          </p>
          <p className="text-sm text-muted-foreground">Last updated: March 1, 2025</p>
        </div>
      </section>

      <section className="py-12 bg-background">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          {/* Quick nav */}
          <div className="grid sm:grid-cols-3 gap-3 mb-12">
            {SECTIONS.map(({ id, icon: Icon, title }) => (
              <a key={id} href={`#${id}`} className="flex items-center gap-2 p-3 rounded-xl bg-card border border-border hover:border-indigo-500/30 transition-all duration-200 text-sm text-muted-foreground hover:text-foreground">
                <Icon className="w-4 h-4 text-indigo-400 flex-shrink-0" />
                <span className="line-clamp-1">{title.replace(/^\d+\.\s/, '')}</span>
              </a>
            ))}
          </div>

          {/* Content */}
          <div className="space-y-10">
            {SECTIONS.map(({ id, icon: Icon, title, content }) => (
              <div key={id} id={id} className="scroll-mt-20">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-9 h-9 rounded-lg bg-gradient-to-br from-indigo-600/20 to-cyan-500/20 flex items-center justify-center">
                    <Icon className="w-4 h-4 text-indigo-400" />
                  </div>
                  <h2 className="font-heading text-xl font-bold text-foreground">{title}</h2>
                </div>
                <div className="pl-12">
                  {content.split('\n\n').map((para, i) => (
                    <p key={i} className="text-muted-foreground leading-relaxed mb-4 text-sm">{para}</p>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-12 p-6 rounded-2xl bg-card border border-border">
            <h3 className="font-heading font-semibold text-foreground mb-2">Questions about this policy?</h3>
            <p className="text-sm text-muted-foreground mb-3">Contact our Data Protection Officer at <strong>privacy@visionex.ai</strong> or write to us at VisionEx Inc., 548 Market St, San Francisco, CA 94105.</p>
          </div>
        </div>
      </section>
    </div>
  );
}
